server:
  servlet:
    context-path: /api
  port: 8123

spring:
  application:
    name: shadow-ai-code-backend

  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_code_shadow?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 522166

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.shadow.aicodingsystem.controller

# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

#AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-0f96007674e64f59849b37c8868f5a27
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
      strict-json-schema: true
      response-format: json_object
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-0f96007674e64f59849b37c8868f5a27
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: true
      log-responses: true

#  web:
#    resources:
#      add-mappings: false
#
#  sql:
#    init:
#      mode: always
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/demo?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true
#    username: root
#    password: 522166
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#logging:
#  level:
#    com.example.demo: INFO
#    com.example: info
#    com.example.demo.user.mapper: debug
#    org.springframework: WARN
#
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] [%X{traceId}] %logger{36} - %msg%n"
#
#  file:
#    name: logs/demo.log
#
#mybatis-plus:
#  mapper-locations: classpath*:/mappers/*.xml
#  type-aliases-package: com.example.demo.domain
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印SQL
#  global-config:
#    db-config:
#      id-type: auto  # 主键自增
#      logic-delete-field: deleted  # 逻辑删除字段名
#      logic-not-delete-value: 0    # 未删除值
#      logic-delete-value: 1        # 已删除值

#mybatis:
#  type-aliases-package: com.example.demo.domain
#  mapper-locations: classpath:mappers/*.xml
#  configuration:
#    map-underscore-to-camel-case: true